# Generated by Django 3.2.7 on 2021-09-23 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageColors',
            fields=[
                ('language', models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French')], max_length=2, primary_key=True, serialize=False)),
                ('color1', models.CharField(max_length=7)),
                ('color2', models.CharField(max_length=7)),
                ('color3', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='HelloWorld',
            fields=[
                ('language', models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French')], max_length=2, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('colors', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello_world.languagecolors')),
            ],
        ),
    ]
